TYPE = exe
SOURCES = test.cpp
INCLUDES = -I/usr/local/include -I$(PWD)/../include/
LIBS =  ../libcryp.a
INSLIBS =  -lrt -lcrypto
OUT = test

#-----------------------------------------------------------------
include ../build.mk