TYPE = lib
SOURCES = md5.cpp pwdhash.cpp base64.cpp hmac.cpp
INCLUDES = -I/usr/local/include -I$(PWD)/../include -I$(PWD)/../../jvar/include
OUT = ../libcryp.a

#-----------------------------------------------------------------
include ../build.mk
