TYPE = lib
SOURCES = md5.cpp pwdhash.cpp base64.cpp hmac.cpp util.cpp str.cpp
INCLUDES = -I/usr/local/include -I$(PWD)/../include
OUT = ../libcryp.a

#-----------------------------------------------------------------
include ../build.mk
